// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3o3wmedh5_v7oLm9cw4y12wNam-51tvo',
    appId: '1:348114043946:web:22916483577d30b6796f53',
    messagingSenderId: '348114043946',
    projectId: 'nuju-coffee',
    authDomain: 'nuju-coffee.firebaseapp.com',
    storageBucket: 'nuju-coffee.firebasestorage.app',
    measurementId: 'G-Z3BQNR0Y6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbAjdMhuvlE9WP_QYv_bHxw34WEoiw8t0',
    appId: '1:348114043946:android:b78dae69c29c6661796f53',
    messagingSenderId: '348114043946',
    projectId: 'nuju-coffee',
    storageBucket: 'nuju-coffee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkOrIlip_CtminG161LF42RHPqe1dsSoQ',
    appId: '1:348114043946:ios:2af21f5881a1cdd4796f53',
    messagingSenderId: '348114043946',
    projectId: 'nuju-coffee',
    storageBucket: 'nuju-coffee.firebasestorage.app',
    iosBundleId: 'com.example.nujucoffee',
  );
}
